### ISSUE TITLE
Cannot Load Music XNB files 

### ISSUE THREAD

**Issue by thedarkprincedc** [RochesterIndiesAnonymous/Ironstag#1]
So far I am having an issue once we load StoryboardXML\\TitleScreenStoryboard and then it tries to load System\Music\TitleScreenBGM we get a System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'

The current build is a 64bit build it may be an issue?????

**Comment by namuol** [comment]
Whoa -- I almost forgot about this repo! Thanks for keeping it alive @thedarkprincedc 😅 

I have no idea how to really make the code live again, but I'm assuming we need to start by porting it to an OSS XNA replacement (of which there are a couple, I believe).

As far as audio assets go, we may try converting it to something like OGG, maybe? I'm guessing there's a chance the OSS library doesn't support MP3.

**Comment by thedarkprincedc** [comment]
Haha, eh no problem. Ive been working on it about a week. I was bored and feeling smart. Also I have a lot of time on my hands, So I figured Id take a crack at it.

Ah its not a problem, I was able to get it to build, and compile on visual studio 2008 just fine. It was a pain in the ass because the installer for XNA 3.1 it doesn't work properly so you have to unzip all the dependencies and run then one by one skipping the xbox live services api installer which causes the installer to throw an exception.

I then converted the project over to Visual Studio 2017, Replaced all the dependencies with monogame 3.7 dependencies, Fixed the function signatures that no longer matched XNA 3.1 (to XNA 4.0 monogame). Right now the content pipeline/reader, and app builds just fine. Its just throwing up on the first loading the music files for the intro. But im pretty sure there is probably more bugs to be uncover

Currently I have a separate branch monogame-conversion I created the project WesternSpaceMono where I have made my changes. I pick the project type to build for Windows, Mac and Linux but the downside you have to use xnb's

**Comment by thedarkprincedc** [comment]
Ill give the *ogg thing a try.

**Comment by thedarkprincedc** [comment]
![image](https://user-images.githubusercontent.com/1664346/42005099-dfbb86b6-7a40-11e8-9757-9f856620ff28.png)

well it works, just gotta work on fixing sound, fonts, build targets and effects

**Comment by josefnpat** [comment]
This is amazing. If you can, please let us attach builds to this repo!

**Comment by namuol** [comment]
@thedarkprincedc Do you have a branch or anything with your changes? Feel free to commit directly and push to `master` if not; otherwise open a PR while it's WIP for those who are curious :)

**Comment by thedarkprincedc** [comment]
Ill post it up soon.

**Comment by thedarkprincedc** [comment]
I got the fonts working today.
- Im going to work on sound again.
- I also have an Issue with the loading of xap xact files (not sure what these are yet. keeps me the level game from starting.)
- Im a very lost with converting effects HLSL to GLSL Shaders (i think its only one of these its a alpha transparency, intro transitions.I disabled this for now)

**Comment by thedarkprincedc** [comment]
Hmmn, tried converting to wav, and ogg. Still failed to load. The mp3 file had issues when I tried to convert them to ogg in ffmpeg cli. I think it said the files were missing header information. I also tried a un related file it still didnt work. I think i may need to look into converting to OpenAL dll's to play background music

**Comment by thedarkprincedc** [comment]
I got the sound working with using song from uri. Using the code from below

//storyboardSong = ScreenManager.Instance.Content.Load<Song>(xdoc.Root.Attribute("Song").Value);

            storyboardSong = Song.FromUri(@"Content\System\Music\TitleScreenBGM.mp3", new Uri(@"Content\System\Music\TitleScreenBGM.mp3", UriKind.Relative));

**Comment by thedarkprincedc** [comment]
I added a patch for this, but there needs to be a content loader designed for loading mp3s to make it cleaner later.

**Comment by thedarkprincedc** [comment]
Hey Guys here are the links to the wip repos @namuol @josefnpat 

https://github.com/RochesterIndiesAnonymous/Ironstag/tree/monogame-conversion
https://github.com/RochesterIndiesAnonymous/Ironstag/tree/develop

Right now im working in the monogame-conversion repo.
I got everything working minus shaders up until game play. The level starts,  

- the life bar shows up
- the backround renders
- the bgm plays
- the player is not rendered, 
- the camera doesnt scroll 
- background tiles disappear.
Also I have to fix sound effects.

![image](https://user-images.githubusercontent.com/1664346/42127486-9eaa050c-7c67-11e8-91c2-5e145c7cced2.png)
![image](https://user-images.githubusercontent.com/1664346/42127490-c396140a-7c67-11e8-96a7-aca7cc3f685a.png)
