### ISSUE TITLE
FX Shader not working

### ISSUE THREAD

**Issue by thedarkprincedc** [RochesterIndiesAnonymous/Ironstag#4]
Shaders are throwing exceptions during story and game screens. I have to convert these from HLSL to GLSL or look into mojoshader for monogame to do this on the fly.

**Comment by thedarkprincedc** [comment]
// SetAlphaValue.fx
float AlphaValue;
sampler2D clrSampler;

float4 ApplyAlphaValue(float2 Tex : TEXCOORD0) : COLOR0
{
	float4 Color;
	Color = tex2D(clrSampler, Tex.xy);
	Color.a *= AlphaValue;
    return Color;
}

technique Technique1
{
    pass Pass1
    {
        PixelShader = compile ps_2_0 ApplyAlphaValue();

    }
}

// Hey @namuol and @josefnpat any idea how id convert this from hlsl to glsl?

**Comment by thedarkprincedc** [comment]
So far I got everything working except this part. The last issue I have left is fixing the build tasks and making sure it can compile for mac, and/or linux and clean up the build directory (better structure). I would like to create content pipeline extensions for loading mp3, and sound effects so they arent hardcoded.

![image](https://user-images.githubusercontent.com/1664346/42134852-0b5316f4-7d11-11e8-8222-fefc56f817f1.png)

**Comment by thedarkprincedc** [comment]
So this is the exception i'm getting ... It looks like the fx effect compiles through the pipeline 

![image](https://user-images.githubusercontent.com/1664346/42135823-a8d6e31c-7d1e-11e8-88c1-7a234c877aca.png)

**Comment by thedarkprincedc** [comment]
Hmmn this looks promising. http://www.monogame.net/documentation/2/?page=2MGFX

**Comment by thedarkprincedc** [comment]
I was able to compile the shader
with 

2MGFX c:\Users\Brett\source\repos\Ironstag\WesternSpaceMono\Content\System\Effects\SetAlphaValue.fx c:\Users\Brett\source\repos\Ironstag\WesternSpaceMono\Content\System\Effects\SetAlphaValue.mgfxd /Profile:DirectX_11

2MGFX c:\Users\Brett\source\repos\Ironstag\WesternSpaceMono\Content\System\Effects\SetAlphaValue.fx c:\Users\Brett\source\repos\Ironstag\WesternSpaceMono\Content\System\Effects\SetAlphaValue.mgfxd /Profile:OpenGL

And I had to upgrade the shader level to compile 
ps_2_0
ps_4_0_level_9_1
Now it loads just fine now i have to fix rendering

**Comment by thedarkprincedc** [comment]
So far when rendering the shader. It doesnt not do a fade out. 
It scales the image smaller and reverses it.

**Comment by namuol** [comment]
Doesn't monogame have something for this built in? It's such a trivial effect... why do we even need a custom shader?

**Comment by thedarkprincedc** [comment]
I feel like there are easier ways of getting this done, but dont think I should avoid learning how shaders work just in case i need them for another project. 

I will add a sepia fade filter to the death animation to see how it looks. 

So far I kinda got the current shader working, ie the alpha level at .25 looks correct. However the image is still flipped for some reason. I had to make changes to sprite batch begin function and add the effect to it. The final fix looks like it may require structural changes but im not sure yet

   // sb.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, null, null, null, null, null);

 sb.Begin(SpriteSortMode.Deferred, BlendState.NonPremultiplied, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, this.alphaEffect);

**Comment by thedarkprincedc** [comment]
I was able to get this effect working however its only when coupled to a sprite.batch begin currently. I have to de couple it so i wont have to change the code.

![image](https://user-images.githubusercontent.com/1664346/42412449-85ea8cda-81da-11e8-9cb2-cc0b3e90f8c4.png)

**Comment by thedarkprincedc** [comment]
Posted this in the wrong area
this shader works perfectly. Ill just modify it to get the effect.

http://community.monogame.net/t/solved-textures-rendering-upside-down-and-small-with-pixel-shader/6345

the only changes i see is the shaderlevel version, screentexture and sampler

**Comment by thedarkprincedc** [comment]
I finally fixed this. The fix involves passing the effect back to the calling function. Its feels a little messy to me but can be refactored.
