### ISSUE TITLE
OSX Build Task

### ISSUE THREAD

**Issue by thedarkprincedc** [RochesterIndiesAnonymous/Ironstag#9]
I tried to build this project on Visual Studio Community/Xamarin on mac. It failed pretty hard.

**Comment by namuol** [comment]
Looking into this too btw -- I'll document anything I learn on the way. :+1:

**Comment by namuol** [comment]
Yeah I'm totally lost... @thedarkprincedc could you link me to any resources you followed to set up the original monogame project? I'm thinking maybe we just need to start over there with OSX in mind (or with any luck, there are just a few things we need to tweak 🤞)

**Comment by thedarkprincedc** [comment]
@namuol, sure. Haha, it really wasn't one resource. Just lots of trial and error and patience. I admit ended just creating a project and clearing out the C# files and copying ours in. That took care most of the assemblies we needed for the project. 

Then building and fixing each error or exception one by one. I thought I picked the project Monogame Mac/Linux/Windows. But I think there is one more article...

http://www.nelsonhurst.com/xna-3-1-to-xna-4-0-cheatsheet/
http://www.gamefromscratch.com/post/2015/06/09/Getting-Started-with-MonoGame-on-MacOS.aspx

**Comment by thedarkprincedc** [comment]
this shader works perfectly. Ill just modify it to get the effect.

http://community.monogame.net/t/solved-textures-rendering-upside-down-and-small-with-pixel-shader/6345

**Comment by thedarkprincedc** [comment]
I saw this file today its in the root of our project. Looks like its a configurarion file. We might only have to change or add a solution platform with the correct compilation/build constant

![image](https://user-images.githubusercontent.com/1664346/42604061-c4ee78d0-853e-11e8-9a4e-6c86f7f29c45.png)

**Comment by thedarkprincedc** [comment]
Looks like im using the wrong monogame framework assemblies. Windows instead of DesktopGL

**Comment by thedarkprincedc** [comment]
Switched Assemblies to DesktopGL now I am getting errors with the when sound files are opened.
I suspects its because I am using OpenAL.
Could not determine container type!

@namuol, Sorry I screwed these up. I need to switch all 
Monogame.Framework
Monogame.Framework.Net
assemblies from Windows to DesktopGL

**Comment by thedarkprincedc** [comment]
It appears to be looking for a ogg files for sounds. I will try and convert our music to ogg.

**Comment by thedarkprincedc** [comment]
Created a branch for this https://github.com/RochesterIndiesAnonymous/Ironstag/tree/desktopgl-conversion it compiles and runs on windows without background music.

**Comment by thedarkprincedc** [comment]
So far I run into compilations errors on the osx side. They seem to be related to the assembly paths. Looks like most changes will be with the build configuration.

**Comment by thedarkprincedc** [comment]
I added the converted mp3 as ogg's to the content pipeline everything compiles and runs on the windows side as opengl.

**Comment by thedarkprincedc** [comment]
http://community.monogame.net/t/solved-cant-build-cross-platform-project/9130

 <Import Project="$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" />

**Comment by thedarkprincedc** [comment]
So currently most of the errors seem to be coming from the *.csproj files for the our content reader and writers. 
We need recreate the Content Pipeline Projects and move our files to them

**Comment by thedarkprincedc** [comment]
Well I got this to compile. I had to make a lot of changes to csproject file. deciding if I should split this or I can add branching to the build instructions.

 Also there is issues with paths to fx, and sounds

![image](https://user-images.githubusercontent.com/1664346/42720568-19648616-86f7-11e8-8420-8897e2f25136.png)

**Comment by thedarkprincedc** [comment]
1. Need to Create Debug | Mac and Release | Mac builds options in vistudio
2. Add Item Groups to csproj to contain mac dependencies and set the condition to respond to a mac build only<ItemGroup condition="selection == 'OSX'"></ItemGroup> use $(EnvVars) for base part of path
3. Fix Content Links sound and fx may need changes for mac vs pc with slashes \ vs /

https://msdn.microsoft.com/en-us/library/bb629388.aspx

**Comment by thedarkprincedc** [comment]
western space mono csproj

<ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="XnaXmlContentPipeline">
      <HintPath>..\XnaXmlContentPipeline\bin\Debug\XnaXmlContentPipeline.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework">
      <HintPath>..\..\..\..\..\Library\Frameworks\MonoGame.framework\v3.6.0.1625\Assemblies\DesktopGL\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework.Net">
      <HintPath>..\..\..\..\..\Library\Frameworks\MonoGame.framework\v3.6.0.1625\Assemblies\DesktopGL\MonoGame.Framework.Net.dll</HintPath>
    </Reference>
    <Reference Include="XnaXmlContentReader">
      <HintPath>..\XnaXmlContentReader\bin\Debug\XnaXmlContentReader.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>

**Comment by thedarkprincedc** [comment]
hmmn it looks like i dont have to create a separate build i just need to fix this pipeline dependency to work on both pc and mac

`  <Reference Include="MonoGame.Framework.Content.Pipeline">
      <HintPath>$(MSBuildExtensionsPath)\MonoGame\v3.0\Tools\MonoGame.Framework.Content.Pipeline.dll</HintPath>
    </Reference>`

**Comment by thedarkprincedc** [comment]
I fixed the cross platform build issue in desktopgl-conversion-mac. However i have to fix paths once again for sound fx and music. due to how files are handled on mac. Ill create separate issues for these.

**Comment by thedarkprincedc** [comment]
https://gist.github.com/BergWerkGIS/4eb166010e995513d308fbb0feabfe35

**Comment by thedarkprincedc** [comment]
Will have to edit proj files like this for other builds
`  <ItemGroup>
    
    <Reference Include="MonoGame.Framework" Condition="'$(OS)' == 'Unix'">
      <HintPath>..\..\..\..\..\Library\Frameworks\MonoGame.framework\v3.0\Assemblies\DesktopGL\MonoGame.Framework.dll</HintPath>
    </Reference>
    <Reference Include="MonoGame.Framework.Content.Pipeline" Condition="'$(OS)' == 'Unix'">
      <HintPath>..\..\..\..\..\Library\Frameworks\MonoGame.framework\v3.0\Tools\MonoGame.Framework.Content.Pipeline.dll</HintPath>
    </Reference>
    
    <Reference Include="MonoGame.Framework, Version=3.6.0.1625, Culture=neutral, processorArchitecture=MSIL" Condition="'$(OS)' != 'Unix'">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\..\..\Program Files (x86)\MonoGame\v3.0\Assemblies\DesktopGL\MonoGame.Framework.dll</HintPath>
    </Reference>
  </ItemGroup>`
